version: "1.0"
info:
  model: int-scaffold
packages:
- name: API1Project
  gitServerName: lakshitha_github
  gitUrl: https://github.com/Lakshitha-Ramesh-IBM
  gitUsername: Lakshitha-Ramesh-IBM
  gitBranch: main
